import Head from "next/head";
import {
  AiOutlineMail,
  AiOutlineLinkedin,
  AiOutlineGithub,
} from "react-icons/ai";
import Image from "next/image";
import barndo from "../public/barndo.jpg";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Brandon Fong Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="home" className="bg-white px-10 ">
        <section className="min-h-screen text-black body-font font-Lato">
          <nav className="py-8 mb-12 flex justify-between ">
            <h1 className="text-xl text-black  rounded-md">Brandon.</h1>
            <ul className="flex items-center">
              <li>
                <a
                  className="bg-gradient-to-r from-blue-400 to-blue-600 text-white px-4 py-2 rounded-md ml-8"
                  href="#home"
                >
                  Home
                </a>

                <a
                  className="bg-gradient-to-r from-blue-400 to-blue-600 text-white px-4 py-2 rounded-md ml-8"
                  href="#PHOTOGRAPHY PAGE?"
                >
                  Photography
                </a>
                <a
                  className="bg-gradient-to-r from-blue-400 to-blue-600 text-white px-4 py-2 rounded-md ml-8"
                  href="#experience"
                >
                  Experience
                </a>
                <a
                  className="bg-gradient-to-r from-blue-400 to-blue-600 text-white px-4 py-2 rounded-md ml-8"
                  href="#contact"
                >
                  Contact
                </a>
                <a
                  className="bg-gradient-to-r from-blue-400 to-blue-600 text-white px-4 py-2 rounded-md ml-8"
                  href="/resume.pdf"
                  target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-8">
            <h2 className="text-6xl py-2 text-blue-600 font-medium">
              Brandon Fong
            </h2>
            <h3 className="text-xl mx-auto p-10 md:px-20 lg:text-3xl md:text-2xl">
              Undergraduate student at the University of Calgary.
            </h3>
          </div>

          <div>
            <Image
              src={barndo}
              className="relative mx-auto rounded-3xl w-80 h-80"
            />
            <p className=" max-w-4xl text-xl mx-auto p-10 md:px-20 lg:text-3xl md:text-2xl">
              Hi!! 👋🏻 My name's Brandon and I am a second-year Electrical
              Engineering student at the University of Calgary, passionate about
              aviation and its applications in modern society. While not
              studying, you can find me doing photography or building mechanical
              keyboards. I am always open to meeting new people, so please feel
              free to connect with me!
            </p>
          </div>
        </section>
        {/* End of the code leading to the photo of me  */}

        <section>
          <div id="experience">
            <h1 className=" lg:text-4xl md:text-3xl text-xl text-black mx-auto text-center pb-8">
              ___ Experience ___
            </h1>
            <ul className="text-black pb-8">
              <p>
                University of Calgary - Web Developer Nov. 2022 – Present •
                Developed a React dashboard web application to aggregate and
                display geothermal drilling data • Utilized React, Python and
                PostgreSQL University of Calgary Solar Car Team - Electrical
                Team Member Oct. 2022 – Present • Improved the wiring and
                organization within car to make it more efficient • Attended
                multiple events to promote the company to prospective students
                Real Canadian Superstore - Produce Clerk Oct. 2019 – Sept. 2022
                • Efficiently addressed customer complaints or concerns in a
                timely fashion • Trained and led 5 new hires to proficiency
              </p>
            </ul>
          </div>
        </section>
        <section id="contact">
          <h1 className=" lg:text-4xl md:text-3xl text-xl text-black mx-auto text-center pb-8">
            ___ Contact ___
          </h1>
          <div className="text-6xl flex justify-center gap-16 pt-2 pb-8 text-gray-800">
            <a
              className="bg-gradient-to-r from-blue-400 to-blue-600 text-white rounded-xl pl-1 pr-1 "
              href="mailto:brandofong02@gmail.com"
              target="_blank"
            >
              <AiOutlineMail />
            </a>
            <a
              className="bg-gradient-to-r from-blue-400 to-blue-600 text-white  rounded-xl"
              href="https://www.linkedin.com/in/brandofong/"
              target="_blank"
            >
              <AiOutlineLinkedin />
            </a>
            <a
              className="bg-gradient-to-r from-blue-400 to-blue-600 text-white  rounded-xl px-0.5"
              href="https://github.com/brandofong"
              target="_blank"
            >
              <AiOutlineGithub />
            </a>
          </div>
        </section>
      </main>
    </div>
  );
}
